version: '2'

services:
  dns-dhcp:
    restart: always
    image: deadpoets/dns-dhcp:1.0
    ports:
    - "53:53/udp"
    - "53:53/tcp"
    - "67:67/udp"
    - "68:68/udp"
    - "10000:10000/tcp"
    volumes:
    - /srv/docker/dns-dhcp:/data
